### ISSUE TITLE
Error: Save Data is corrupted.

### ISSUE THREAD

**Issue by coinfactory** [VisualStudio-zz/MLSSE#1]
Opening game after injecting save leads to error message with the modded save deleted by the system.

**Comment by GoobyCorp** [comment]
I need the command you ran and your unmodded save please.

**Comment by coinfactory** [comment]
I fixed the problem, had to toggle secure value off in JKSM.

**Comment by GoobyCorp** [comment]
May I ask what command you used anyway so I can confirm it's working completely?

**Comment by coinfactory** [comment]
-o ML1_001.sav

**Comment by GoobyCorp** [comment]
Thanks but that won't mod anything on the game lol
